#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  custom:
    test:
      - parallel:
          - step:
              name: Build and Test
              caches:
                - node
              script:
                - npm install
                - npm run cover
          - step:
              name: Code linting
              script:
                - npm install
                - npm run lint
              caches:
                - node
  branches:
    dev-disabled:
      - step:
          name: Build and Push Image, and release
          deployment: Test
          script:
            - echo \
              'machine machine api.heroku.com
                login $heroku_username
                password $heroku_password' > ~/.netrc
            - docker login --username=$heroku_username --password=$heroku_password registry.heroku.com
            - curl https://cli-assets.heroku.com/install.sh | sh
            - cd deploy; sh build.sh
            - IMAGE_NAME="dsh-fastify-auth-api/web"
            - docker push registry.heroku.com/$IMAGE_NAME
            - heroku container:release web --app dsh-fastify-auth-api
          services:
            - docker
          caches:
            - docker

